HTML Semaforo TOP3 FINAL = 

-- 1. Tabla base con métricas
VAR _base =
    SUMMARIZE(
        'Registro Tareas',
        'Registro Tareas'[id_maquina],
        "tot",   CALCULATE(COUNTROWS('Registro Tareas')),
        "comp",  CALCULATE(COUNTROWS('Registro Tareas'), 'Registro Tareas'[estado] = "Completado")
    )

-- 2. Metadatos
VAR _tabla =
    ADDCOLUMNS(
        _base,
        "impl",    LOOKUPVALUE(Maquinas[implementado], Maquinas[id_maquina], 'Registro Tareas'[id_maquina]),
        "nom",     LOOKUPVALUE(Maquinas[nombre],       Maquinas[id_maquina], 'Registro Tareas'[id_maquina]),
        "lin",     LOOKUPVALUE(Maquinas[linea],        Maquinas[id_maquina], 'Registro Tareas'[id_maquina]),
        "pctNum",  DIVIDE([comp], [tot], 0)
    )

VAR _filtrado = FILTER(_tabla, [impl] = TRUE() && [tot] > 0)
VAR _hasProblem = COUNTROWS(FILTER(_filtrado, [pctNum] < 0.80)) > 0

-- 3. Construcción de filas (Interacción por Clic)
VAR _filas =
    CONCATENATEX(
        TOPN(3, _filtrado, [pctNum], ASC),

        VAR _n      = [nom]
        VAR _l      = [lin]
        VAR _p      = COALESCE([pctNum], 0)
        VAR _pctInt = INT(_p * 100)
        VAR _lbl    = _pctInt & "%"
        
        VAR _col = IF(_p < 0.75,"#D32F2F", IF(_p < 0.80,"#F9A825","#00A651"))
        VAR _pill = IF(_p < 0.75,"pill-r", IF(_p < 0.80,"pill-a","pill-g"))
        VAR _rowClass = IF(_hasProblem && _p < 0.80,"row bad","row")

        RETURN
            "<div class='" & _rowClass & "'>"
            & "<div class='ind' style='background:" & _col & "'></div>"
            & "<div class='info'><div class='mn'>" & IF(ISBLANK(_n), [id_maquina], _n) & "</div><div class='ms'>" & IF(ISBLANK(_l), "—", _l) & "</div></div>"
            & "<div class='bt'><div class='bf' style='width:" & _pctInt & "%;background:" & _col & "'></div></div>"
            & "<div class='metrics'>"
            & "  <span class='pv' style='color:" & _col & "'>" & _lbl & "</span>"
            & "  <span class='" & _pill & "'>" & IF(_p < 0.75,"CRITICO", IF(_p < 0.80,"ALERTA","OK")) & "</span>"
            & "</div>"
            & "</div>",
        ""
    )

RETURN
"<style>
*{margin:0;padding:0;box-sizing:border-box}
html,body{width:100%;height:100%;overflow:hidden;font-family:'Segoe UI',sans-serif;}
.wrap{width:100%;height:210px;background:#FFFFFF;border-radius:10px;border:1px solid #E3E3E3;border-top:3px solid " & IF(_hasProblem, "#D32F2F", "#00A651") & ";padding:12px;display:flex;flex-direction:column;}
.lbl{font-size:10px;font-weight:600;text-transform:uppercase;color:#6b6b6b;margin-bottom:8px;}
.rows{display:flex;flex-direction:column;gap:8px;flex:1;}
.row{display:flex;align-items:center;gap:10px;padding:8px 12px;border-radius:8px;background:#FAFAFA;transition:all 0.2s ease;}
.row:hover{background:#F3F4F6;}
.row.bad{background:rgba(211,47,47,0.05);border:1px solid rgba(211,47,47,0.15);}
.ind{width:8px;height:8px;border-radius:50%;flex-shrink:0;}
.info{width:110px;flex-shrink:0;}
.mn{font-size:10px;font-weight:600;color:#111827;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
.ms{font-size:8px;color:#9CA3AF;}
.bt{flex:1;height:6px;background:#EEEEEE;border-radius:3px;overflow:hidden;}
.bf{height:100%;border-radius:3px;transform-origin:left;animation:grow 0.8s ease-out forwards;}
@keyframes grow{from{transform:scaleX(0);}to{transform:scaleX(1);}}
.metrics{display:flex;align-items:center;gap:8px;flex-shrink:0;}
.pv{font-size:11px;font-weight:700;width:35px;text-align:right;}
.pill-g, .pill-a, .pill-r{font-size:8px;font-weight:700;width:55px;text-align:center;padding:3px 0;border-radius:20px;}
.pill-g{background:rgba(0,166,81,.1);color:#00A651;}
.pill-a{background:rgba(249,168,37,.1);color:#F9A825;}
.pill-r{background:rgba(211,47,47,.1);color:#D32F2F;}
</style>
<div class='wrap'>
  <div class='lbl'>Máquinas Prioritarias</div>
  <div class='rows'>" & _filas & "</div>
</div>"