HTML KPIs FINAL PRO = 
VAR _pct       = COALESCE([% Cumplimiento],0)
VAR _comp      = COALESCE([Total Completadas],0)
VAR _atr       = COALESCE([Total Atrasadas],0)
VAR _total     = COALESCE([Total Registros],0)

-- Máquinas implementadas (total fijo desde Maquinas)
VAR _maqImpl   = CALCULATE(COUNTROWS(Maquinas), Maquinas[implementado] = TRUE())
VAR _maqTotal  = COUNTROWS(Maquinas)

/* BARRAS */
VAR _pctBar  = FORMAT(_pct * 100, "0")
VAR _compBar = FORMAT(DIVIDE(_comp, _total, 0) * 100, "0")
VAR _atrBar  = FORMAT(DIVIDE(_atr,  _total, 0) * 100, "0")
VAR _maqBar  = FORMAT(DIVIDE(_maqImpl, _maqTotal, 0) * 100, "0")

/* COLORES CORPORATIVOS */
VAR _Green  = "#00A651"
VAR _Red    = "#D32F2F"
VAR _Yellow = "#F9A825"
VAR _Blue   = "#0078D4"

VAR _ColorCumpl =
    IF(_pct < 0.75, _Red,
    IF(_pct < 0.80, _Yellow, _Green))

VAR _CtxCumpl =
    IF(_pct < 0.75, "RIESGO",
    IF(_pct < 0.80, "ALERTA", "EN META"))

VAR _ColorAtr =
    IF(_atr = 0, _Green, _Red)

VAR _CtxAtr =
    IF(_atr = 0, "SIN DESVIACIONES",
    IF(_atr < 5, "ALERTA", "CRÍTICO"))

RETURN
"<style>
    *{margin:0;padding:0;box-sizing:border-box;}
    html,body{width:100%;height:100%;overflow:hidden;font-family:'Segoe UI', sans-serif;background:transparent;}
    
    .wrap{display:flex;gap:10px;padding:8px;width:100%;height:110px;}
    
    .kpi{
        flex:1;background:#FFFFFF;
        border-radius:12px;border:1px solid #E3E3E3;
        padding:10px 14px;display:flex;flex-direction:column;justify-content:space-between;
        position:relative;overflow:hidden;
    }
    
    /* Barra superior de color */
    .kpi::before {
        content: ''; position: absolute; top: 0; left: 0; width: 100%; height: 4px;
    }
    .kpi.cumpl::before { background: " & _ColorCumpl & "; }
    .kpi.comp::before { background: " & _Green & "; }
    .kpi.atras::before { background: " & _ColorAtr & "; }
    .kpi.maq::before { background: " & _Blue & "; }

    .kpi-lbl{font-size:10px;font-weight:600;text-transform:uppercase;color:#6B7280;letter-spacing:0.3px;}
    .kpi-num{font-size:24px;font-weight:700;line-height:1.1;margin:2px 0;}
    .ctx{font-size:9px;font-weight:700;}
    .kpi-sub{font-size:9px;color:#9CA3AF;}
    
    .track{height:6px;background:#F3F4F6;border-radius:3px;margin-top:6px;overflow:hidden;}
    .fill{
        height:100%;border-radius:3px;transform-origin:left;
        animation:growBar 0.8s ease-out forwards;
    }
    @keyframes growBar{from{transform:scaleX(0);}to{transform:scaleX(1);}}
</style>

<div class='wrap'>

  <!-- CUMPLIMIENTO -->
  <div class='kpi cumpl'>
    <div class='kpi-lbl'>Cumplimiento</div>
    <div class='kpi-num' style='color:" & _ColorCumpl & "'>" & FORMAT(_pct,"0.0%") & "</div>
    <div class='ctx' style='color:" & _ColorCumpl & "'>" & _CtxCumpl & "</div>
    <div class='track'><div class='fill' style='width:" & _pctBar & "%;background:" & _ColorCumpl & "'></div></div>
  </div>

  <!-- COMPLETADAS -->
  <div class='kpi comp'>
    <div class='kpi-lbl'>Completadas</div>
    <div class='kpi-num' style='color:" & _Green & "'>" & FORMAT(_comp,"#,0") & "</div>
    <div class='kpi-sub'>de " & FORMAT(_total,"#,0") & " tareas</div>
    <div class='track'><div class='fill' style='width:" & _compBar & "%;background:" & _Green & "'></div></div>
  </div>

  <!-- ATRASADAS -->
  <div class='kpi atras'>
    <div class='kpi-lbl'>Atrasadas</div>
    <div class='kpi-num' style='color:" & _ColorAtr & "'>" & FORMAT(_atr,"#,0") & "</div>
    <div class='ctx' style='color:" & _ColorAtr & "'>" & _CtxAtr & "</div>
    <div class='track'><div class='fill' style='width:" & _atrBar & "%;background:" & _ColorAtr & "'></div></div>
  </div>

  <!-- MAQUINAS IMPLEMENTADAS -->
  <div class='kpi maq'>
    <div class='kpi-lbl'>Máquinas Implementadas</div>
    <div class='kpi-num' style='color:" & _Blue & "'>" & FORMAT(_maqImpl,"#,0") & "</div>
    <div class='kpi-sub'>" & FORMAT(_maqBar, "0") & "% del total</div>
    <div class='track'><div class='fill' style='width:" & _maqBar & "%;background:" & _Blue & "'></div></div>
  </div>

</div>"
