HTML Cards + Detalle = 
VAR _areaActual = SELECTEDVALUE('Areas Filtro'[area])
VAR _areaLabel  = COALESCE(_areaActual, "Todas las áreas")
VAR _areaJS     = IF(_areaActual = "Todas" || ISBLANK(_areaActual), "", _areaActual)

-- ✅ Iterar Maquinas, no Semaforo Maquina
VAR _filas =
    CONCATENATEX(
        FILTER(Maquinas, Maquinas[implementado] = TRUE()),
        VAR _id   = Maquinas[id_maquina]
        VAR _nom  = Maquinas[nombre]
        VAR _lin  = Maquinas[linea]
        VAR _area = Maquinas[area]
        VAR _pct  = CALCULATE([Cumplimiento Maquina %],  'Registro Tareas'[id_maquina] = _id)
        VAR _comp = CALCULATE([Total Completadas],        'Registro Tareas'[id_maquina] = _id)
        VAR _tot  = CALCULATE([Total Registros],          'Registro Tareas'[id_maquina] = _id)
        VAR _atr  = CALCULATE([Total Atrasadas],          'Registro Tareas'[id_maquina] = _id)
        VAR _pendVigentes =
            CALCULATE(
                COUNTROWS('Registro Tareas'),
                'Registro Tareas'[id_maquina]   = _id,
                'Registro Tareas'[estado]       = "Pendiente",
                'Registro Tareas'[fecha_limite] >= NOW()
            )
        VAR _pendVencidos =
            CALCULATE(
                COUNTROWS('Registro Tareas'),
                'Registro Tareas'[id_maquina]   = _id,
                'Registro Tareas'[estado]       = "Pendiente",
                'Registro Tareas'[fecha_limite] < NOW()
            )
        VAR _atrMaq =
            CALCULATE(
                COUNTROWS('Registro Tareas'),
                'Registro Tareas'[id_maquina] = _id,
                'Registro Tareas'[estado]     = "Atrasado"
            )
        VAR _esCritico  = _atrMaq > 0
        VAR _esEnCurso  = NOT _esCritico && (_pendVigentes > 0 || _pendVencidos > 0)
        VAR _col =
            IF(_esCritico, "#D32F2F",
            IF(_esEnCurso, "#D97706",
            "#00A651"))
        VAR _est =
            IF(_esCritico, "CRÍTICO",
            IF(_esEnCurso, "EN CURSO",
            "OK"))
        VAR _bar = FORMAT(_pct * 100, "0")
        VAR _bc =
            IF(_esCritico, "r",
            IF(_esEnCurso, "a",
            "g"))
        RETURN
            "<div class='mc' data-id='" & _id & "' data-nom='" & _nom & "' data-lin='" & _lin & "' data-area='" & _area & "' onclick='selectMaq(this)'>"
            & "<div class='mct " & _bc & "'></div>"
            & "<div class=mcb>"
            & "<div class=mc-name>" & _nom & "</div>"
            & "<div class=mc-lin>" & _lin & "</div>"
            & "<div class=mc-pct style=color:" & _col & ">" & FORMAT(_pct,"0.0%") & "</div>"
            & "<div class=mc-sub>" & FORMAT(_comp,"0") & " / " & FORMAT(_tot,"0") & "</div>"
            & "<div class=track><div class=fill style=width:" & _bar & "%;background:" & _col & "></div></div>"
            & "<div class=mc-foot>"
            & "<span class=mc-est style=color:" & _col & ">" & _est & "</span>"
            & IF(_atr > 0, "<span class=mc-atr>⚠ " & FORMAT(_atr,"0") & "</span>", "")
            & "</div>"
            & "</div></div>",
        ""
    )

-- ✅ No implementadas
VAR _noImpl =
    CONCATENATEX(
        FILTER(Maquinas, Maquinas[implementado] = FALSE()),
        VAR _nom  = Maquinas[nombre]
        VAR _lin  = Maquinas[linea]
        VAR _area = Maquinas[area]
        RETURN
            "<div class='mc nd' data-lin='" & _lin & "' data-area='" & _area & "'>"
            & "<div class='mct nd-t'></div>"
            & "<div class=mcb>"
            & "<div class=mc-name>" & _nom & "</div>"
            & "<div class=mc-lin>" & _lin & "</div>"
            & "<div class=mc-pct style=color:#9CA3AF>—</div>"
            & "<div class=mc-sub>Sin datos</div>"
            & "<div class=track></div>"
            & "<div class=mc-foot><span class=mc-nd>En implementación</span></div>"
            & "</div></div>",
        ""
    )

-- ✅ SECCIÓN 1: Atrasadas + Aplazadas
VAR _filasAtr =
    CONCATENATEX(
        TOPN(50,
            FILTER('Registro Tareas',
                'Registro Tareas'[estado] = "Atrasado" ||
                'Registro Tareas'[veces_aplazada] > 0
            ),
            'Registro Tareas'[fecha_periodo], ASC
        ),
        VAR _idtarea = 'Registro Tareas'[id_tarea]
        VAR _idmaq   = 'Registro Tareas'[id_maquina]
        VAR _fecha   = FORMAT('Registro Tareas'[fecha_periodo], "DD MMM")
        VAR _periodo = 'Registro Tareas'[fecha_periodo]
        VAR _estado  = 'Registro Tareas'[estado]
        VAR _motivo  = 'Registro Tareas'[motivo_bloqueo]
        VAR _veces   = 'Registro Tareas'[veces_aplazada]
        VAR _turno   = 'Registro Tareas'[turno]
        VAR _tarea   = LOOKUPVALUE(Tareas[nombre_tarea], Tareas[id_tarea],     _idtarea)
        VAR _tipo    = LOOKUPVALUE(Tareas[tipo],         Tareas[id_tarea],     _idtarea)
        VAR _freq    = LOOKUPVALUE(Tareas[frecuencia],   Tareas[id_tarea],     _idtarea)
        VAR _maq     = LOOKUPVALUE(Maquinas[nombre],     Maquinas[id_maquina], _idmaq)
        VAR _lin     = LOOKUPVALUE(Maquinas[linea],      Maquinas[id_maquina], _idmaq)
        VAR _impl    = LOOKUPVALUE(Maquinas[implementado], Maquinas[id_maquina], _idmaq)
        VAR _implVal = IF(_impl = TRUE(), "1", "0")
        -- 🔄 NUEVO: Lookup operador
        VAR _idop    = 'Registro Tareas'[id_operador]
        VAR _opName  = LOOKUPVALUE(Operadores[nombreoperador], Operadores[id_operador], _idop)
        VAR _opFoto  = LOOKUPVALUE(Operadores[foto_operador], Operadores[id_operador], _idop)
        VAR _tareaLbl   = IF(ISBLANK(_tarea), "Sin nombre", _tarea)
        VAR _tipoLbl    = IF(ISBLANK(_tipo),  "—", LEFT(_tipo, 4))
        VAR _freqLbl    = IF(ISBLANK(_freq),  "—", _freq)
        VAR _maqLbl     = IF(ISBLANK(_maq),   _idmaq, _maq)
        VAR _linLbl     = IF(ISBLANK(_lin),   "", _lin)
        VAR _turnoLbl   = IF(ISBLANK(_turno), "Todo el día", _turno)
        VAR _dias       = FORMAT(DATEDIFF(_periodo, TODAY(), DAY), "0")
        VAR _esAplaz    = _veces > 0
        VAR _borderColor = IF(_esAplaz, "#D97706", "#D32F2F")
        VAR _badgeClass  = IF(_esAplaz, "ep-ap", "ep-a")
        VAR _badgeLbl    = IF(_esAplaz, "Aplazado", "Atrasado")
        VAR _subLbl      = IF(_esAplaz,
            _maqLbl & " · " & FORMAT(_veces,"0") & "x aplazada",
            _maqLbl & " · " & _dias & "d atr."
        )
        VAR _motivoSafe = IF(ISBLANK(_motivo), "Sin motivo registrado", _motivo)
        RETURN
            "<div class='drow' data-maq='" & _idmaq & "' data-lin='" & _linLbl & "' data-impl='" & _implVal & "' data-motivo='" & _motivoSafe & "' data-aplaz='" & IF(_esAplaz,"1","0") & "' data-tarea='" & _tareaLbl & "' data-maqnom='" & _maqLbl & "' data-op='" & COALESCE(_opName,"Sin asignar") & "' data-opfoto='" & COALESCE(_opFoto,"") & "' data-estado='" & _badgeLbl & "' data-tipofull='" & COALESCE(_tipo,"—") & "' data-freq='" & _freqLbl & "' data-fplan='" & FORMAT(_periodo,"DD/MM/YYYY") & "' data-fcomp='—' data-turno='" & _turnoLbl & "' data-linea='" & _linLbl & "' style='border-left:2px solid " & _borderColor & "' onclick='onRowClick(this)'>"
            & "<div class=c1><div class=t-main>" & _tareaLbl & "</div><div class=t-sub>" & _subLbl & "</div></div>"
            & "<div class=c2><span class=tag>" & _tipoLbl & "</span></div>"
            & "<div class=c3>" & _freqLbl & "</div>"
            & "<div class=c4>" & _fecha & "</div>"
            & "<div class=c5><span class='" & _badgeClass & "'>" & _badgeLbl & "</span></div>"
            & "<div class=c6>" & _turnoLbl & "</div>"
            & "</div>",
        ""
    )

-- ✅ SECCIÓN 2: Pendientes puras
VAR _filasP =
    CONCATENATEX(
        SUMMARIZE(
            FILTER('Registro Tareas',
                'Registro Tareas'[estado]         = "Pendiente" &&
                'Registro Tareas'[veces_aplazada] = 0
            ),
            'Registro Tareas'[id_tarea],
            'Registro Tareas'[id_maquina],
            'Registro Tareas'[fecha_periodo]
        ),
        VAR _idtarea = 'Registro Tareas'[id_tarea]
        VAR _idmaq   = 'Registro Tareas'[id_maquina]
        VAR _periodo = 'Registro Tareas'[fecha_periodo]
        VAR _idop = CALCULATE(MAX('Registro Tareas'[id_operador]), 'Registro Tareas'[id_tarea]=_idtarea, 'Registro Tareas'[id_maquina]=_idmaq, 'Registro Tareas'[fecha_periodo]=_periodo)
        VAR _opName = LOOKUPVALUE(Operadores[nombreoperador], Operadores[id_operador], _idop)
        VAR _opFoto = LOOKUPVALUE(Operadores[foto_operador], Operadores[id_operador], _idop)
        VAR _tieneOp =
            CALCULATE(
                COUNTROWS('Registro Tareas'),
                'Registro Tareas'[id_tarea]      = _idtarea,
                'Registro Tareas'[id_maquina]    = _idmaq,
                'Registro Tareas'[fecha_periodo] = _periodo,
                NOT ISBLANK('Registro Tareas'[id_operador])
            ) > 0
        VAR _turnoLbl =
            IF(_tieneOp,
                CALCULATE(
                    MAX('Registro Tareas'[turno]),
                    'Registro Tareas'[id_tarea]      = _idtarea,
                    'Registro Tareas'[id_maquina]    = _idmaq,
                    'Registro Tareas'[fecha_periodo] = _periodo
                ),
                "Todo el día"
            )
        VAR _fecha    = FORMAT(_periodo, "DD MMM")
        VAR _tarea    = LOOKUPVALUE(Tareas[nombre_tarea], Tareas[id_tarea],     _idtarea)
        VAR _tipo     = LOOKUPVALUE(Tareas[tipo],         Tareas[id_tarea],     _idtarea)
        VAR _freq     = LOOKUPVALUE(Tareas[frecuencia],   Tareas[id_tarea],     _idtarea)
        VAR _maq      = LOOKUPVALUE(Maquinas[nombre],     Maquinas[id_maquina], _idmaq)
        VAR _lin      = LOOKUPVALUE(Maquinas[linea],      Maquinas[id_maquina], _idmaq)
        VAR _impl     = LOOKUPVALUE(Maquinas[implementado], Maquinas[id_maquina], _idmaq)
        VAR _implVal  = IF(_impl = TRUE(), "1", "0")
        VAR _tareaLbl = IF(ISBLANK(_tarea), "Sin nombre", _tarea)
        VAR _tipoLbl  = IF(ISBLANK(_tipo),  "—", LEFT(_tipo, 4))
        VAR _freqLbl  = IF(ISBLANK(_freq),  "—", _freq)
        VAR _maqLbl   = IF(ISBLANK(_maq),   _idmaq, _maq)
        VAR _linLbl   = IF(ISBLANK(_lin),   "", _lin)
        RETURN
            "<div class='drow' onclick='onRowClick(this)' data-maq='" & _idmaq & "' data-lin='" & _linLbl & "' data-impl='" & _implVal & "' data-tarea='" & _tareaLbl & "' data-maqnom='" & _maqLbl & "' data-op='" & COALESCE(_opName,"Sin asignar") & "' data-opfoto='" & COALESCE(_opFoto,"") & "' data-estado='Pendiente' data-tipofull='" & COALESCE(_tipo,"—") & "' data-freq='" & _freqLbl & "' data-fplan='" & FORMAT(_periodo,"DD/MM/YYYY") & "' data-fcomp='—' data-turno='" & _turnoLbl & "' data-linea='" & _linLbl & "' data-motivo='' style='border-left:2px solid #0078D4'>"
            & "<div class=c1><div class=t-main>" & _tareaLbl & "</div><div class=t-sub>" & _maqLbl & "</div></div>"
            & "<div class=c2><span class=tag>" & _tipoLbl & "</span></div>"
            & "<div class=c3>" & _freqLbl & "</div>"
            & "<div class=c4>" & _fecha & "</div>"
            & "<div class=c5><span class=ep-p>Pendiente</span></div>"
            & "<div class=c6>" & _turnoLbl & "</div>"
            & "</div>",
        ""
    )

-- ✅ SECCIÓN 3: Completadas
VAR _filasComp =
    CONCATENATEX(
        TOPN(50,
            FILTER('Registro Tareas', 'Registro Tareas'[estado] = "Completado"),
            'Registro Tareas'[fecha_completado], DESC
        ),
        VAR _idtarea = 'Registro Tareas'[id_tarea]
        VAR _idmaq   = 'Registro Tareas'[id_maquina]
        VAR _fecha   = FORMAT('Registro Tareas'[fecha_periodo], "DD MMM")
        VAR _turno   = 'Registro Tareas'[turno]
        VAR _tarea   = LOOKUPVALUE(Tareas[nombre_tarea], Tareas[id_tarea],     _idtarea)
        VAR _tipo    = LOOKUPVALUE(Tareas[tipo],         Tareas[id_tarea],     _idtarea)
        VAR _freq    = LOOKUPVALUE(Tareas[frecuencia],   Tareas[id_tarea],     _idtarea)
        VAR _maq     = LOOKUPVALUE(Maquinas[nombre],     Maquinas[id_maquina], _idmaq)
        VAR _lin     = LOOKUPVALUE(Maquinas[linea],      Maquinas[id_maquina], _idmaq)
        VAR _foto    = 'Registro Tareas'[foto_evidencia]
        VAR _idop    = 'Registro Tareas'[id_operador]
        VAR _opName  = LOOKUPVALUE(Operadores[nombreoperador], Operadores[id_operador], _idop)
        VAR _opFoto  = LOOKUPVALUE(Operadores[foto_operador], Operadores[id_operador], _idop)
        VAR _fcomp   = 'Registro Tareas'[fecha_completado]
        VAR _tareaLbl   = IF(ISBLANK(_tarea), "Sin nombre", _tarea)
        VAR _tipoLbl    = IF(ISBLANK(_tipo),  "—", LEFT(_tipo, 4))
        VAR _freqLbl    = IF(ISBLANK(_freq),  "—", _freq)
        VAR _maqLbl     = IF(ISBLANK(_maq),   _idmaq, _maq)
        VAR _linLbl     = IF(ISBLANK(_lin),   "", _lin)
        VAR _turnoLbl   = IF(ISBLANK(_turno), "Todo el día", _turno)
        VAR _tieneFoto  = NOT ISBLANK(_foto)
        VAR _fotoAttr   = IF(_tieneFoto, _foto, "")
        VAR _camIcon    =
            IF(_tieneFoto,
                "<span class=cam-btn onclick='showEvidencia(this)' data-url='" & _fotoAttr & "' data-tarea='" & _tareaLbl & "' title='Ver evidencia'>&#128247;</span>",
                "<span class=cam-no title='Sin evidencia'>&#128247;</span>"
            )
        RETURN
            "<div class='drow' onclick='onRowClick(this)' data-maq='" & _idmaq & "' data-lin='" & _linLbl & "' data-tarea='" & _tareaLbl & "' data-maqnom='" & _maqLbl & "' data-op='" & COALESCE(_opName,"—") & "' data-opfoto='" & COALESCE(_opFoto,"") & "' data-estado='Completado' data-tipofull='" & COALESCE(_tipo,"—") & "' data-freq='" & _freqLbl & "' data-fplan='" & FORMAT('Registro Tareas'[fecha_periodo],"DD/MM/YYYY") & "' data-fcomp='" & IF(ISBLANK(_fcomp),"—",FORMAT(_fcomp,"DD/MM HH:mm")) & "' data-turno='" & _turnoLbl & "' data-linea='" & _linLbl & "' data-motivo='' style=border-left:2px solid #00A651>"
            & "<div class=c1><div class=t-main>" & _tareaLbl & "</div><div class=t-sub>" & _maqLbl & "</div></div>"
            & "<div class=c2><span class=tag>" & _tipoLbl & "</span></div>"
            & "<div class=c3>" & _freqLbl & "</div>"
            & "<div class=c4>" & _fecha & "</div>"
            & "<div class='c5 c5-comp'><span class=ep-c>Completado</span>" & _camIcon & "</div>"
            & "<div class=c6>" & _turnoLbl & "</div>"
            & "</div>",
        ""
    )

VAR _detalleFilas = _filasAtr & _filasP & _filasComp
VAR _comp  = [Total Completadas]
VAR _atr   = [Total Atrasadas]
VAR _total = [Total Registros]

RETURN
"<style>"
& "* {margin:0;padding:0;box-sizing:border-box}"
& "html,body{width:100%;height:100%;background:transparent;font-family:sans-serif;overflow:hidden;}"
& ".wrap{width:100%;height:100%;display:flex;flex-direction:column;gap:4px;padding:8px;}"
& ".g-hdr{display:flex;align-items:center;justify-content:space-between;flex-shrink:0;}"
& ".g-title{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#9CA3AF;}"
& ".g-ctx{font-size:8px;color:#9CA3AF;}"
& ".lin-tabs{display:flex;gap:4px;flex-shrink:0;min-height:24px;flex-wrap:wrap;}"
& ".ltab{padding:3px 12px;border-radius:20px;border:1px solid #E3E3E3;background:#fff;font-size:8.5px;font-weight:600;color:#6B7280;cursor:pointer;transition:all .15s;}"
& ".ltab:hover{border-color:#0078D4;color:#0078D4;}"
& ".ltab.active{background:#0078D4;color:#fff;border-color:#0078D4;}"
& ".cards-zone{display:flex;align-items:center;gap:6px;flex-shrink:0;height:140px;}"
& ".nav-btn{width:22px;height:22px;border-radius:50%;border:1px solid #E3E3E3;background:#fff;cursor:pointer;font-size:10px;color:#6B7280;flex-shrink:0;transition:all .15s;display:flex;align-items:center;justify-content:center;}"
& ".nav-btn:hover{border-color:#00A651;color:#00A651;background:rgba(0,166,81,.06);}"
& ".maq-row{display:flex;gap:8px;overflow-x:auto;overflow-y:hidden;flex:1;height:100%;scroll-behavior:smooth;padding-bottom:4px;align-items:stretch;}"
& ".maq-row::-webkit-scrollbar{height:3px;}"
& ".maq-row::-webkit-scrollbar-thumb{background:#E3E3E3;border-radius:2px;}"
& ".mc{background:#F4F5F7;border:1px solid #E3E3E3;border-radius:8px;min-width:145px;max-width:145px;display:flex;flex-direction:column;flex-shrink:0;overflow:hidden;transition:all .15s;cursor:pointer;}"
& ".mc:hover{background:#fff;box-shadow:0 3px 10px rgba(0,0,0,.1);transform:translateY(-2px);}"
& ".mc.selected{background:#fff;border-color:#0078D4;box-shadow:0 0 0 2px rgba(0,120,212,.15);transform:translateY(-2px);}"
& ".mc.hidden{display:none;}"
& ".nd{border-style:dashed;opacity:.5;cursor:default;}"
& ".nd:hover{transform:none;box-shadow:none;}"
& ".mct{height:3px;flex-shrink:0;}"
& ".mct.g{background:#00A651;}.mct.a{background:#D97706;}.mct.r{background:#D32F2F;}.nd-t{background:#E3E3E3;}"
& ".mcb{padding:8px 10px;display:flex;flex-direction:column;gap:2px;}"
& ".mc-name{font-size:10px;font-weight:700;color:#111827;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}"
& ".mc-lin{font-size:7px;color:#9CA3AF;text-transform:uppercase;letter-spacing:.5px;margin-bottom:2px;}"
& ".mc-pct{font-size:18px;font-weight:800;line-height:1;letter-spacing:-1px;}"
& ".mc-sub{font-size:7px;color:#9CA3AF;margin-top:1px;}"
& ".track{height:2px;background:#EEEEEE;border-radius:2px;margin-top:6px;}"
& ".fill{height:2px;border-radius:2px;}"
& ".mc-foot{display:flex;align-items:center;justify-content:space-between;margin-top:4px;}"
& ".mc-est{font-size:7px;font-weight:700;text-transform:uppercase;letter-spacing:.3px;}"
& ".mc-atr{font-size:7px;color:#D32F2F;font-weight:600;}"
& ".mc-nd{font-size:7px;color:#9CA3AF;font-style:italic;}"
& ".table-zone{flex:1;min-height:0;background:#fff;border-radius:10px;border:1px solid #E3E3E3;border-top:3px solid #0078D4;display:flex;flex-direction:column;overflow:hidden;padding:8px 12px;}"
& ".t-hdr{display:flex;align-items:center;gap:8px;margin-bottom:6px;flex-shrink:0;}"
& ".t-hdr-title{font-size:10px;font-weight:700;color:#111827;}"
& ".t-hdr-sub{font-size:8px;color:#9CA3AF;}"
& ".clear-btn{margin-left:auto;font-size:8px;color:#0078D4;cursor:pointer;padding:2px 8px;border-radius:4px;border:1px solid rgba(0,120,212,.3);background:rgba(0,120,212,.05);display:none;}"
& ".clear-btn:hover{background:rgba(0,120,212,.12);}"
& ".thdr{display:grid;grid-template-columns:2.5fr .6fr .8fr .7fr .9fr .7fr;gap:8px;padding:4px 10px;font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.8px;color:#9CA3AF;border-bottom:1px solid #F3F4F6;margin-bottom:2px;flex-shrink:0;}"
& ".dscroll{flex:1;overflow-y:auto;overflow-x:hidden;min-height:0;}"
& ".dscroll::-webkit-scrollbar{width:3px;}"
& ".dscroll::-webkit-scrollbar-thumb{background:#E3E3E3;border-radius:2px;}"
& ".drow{display:grid;grid-template-columns:2.5fr .6fr .8fr .7fr .9fr .7fr;gap:8px;padding:5px 10px;align-items:center;border-radius:6px;margin-bottom:2px;}"
& ".drow:hover{background:rgba(0,0,0,.03);}"
& ".drow.hidden{display:none;}"
& ".c1{min-width:0;}"
& ".t-main{font-size:10px;font-weight:600;color:#111827;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}"
& ".t-sub{font-size:7.5px;color:#9CA3AF;margin-top:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}"
& ".c2,.c3,.c4,.c6{font-size:9px;color:#6B7280;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}"
& ".tag{font-size:7.5px;padding:2px 6px;border-radius:4px;background:rgba(0,0,0,.05);color:#6B7280;font-weight:600;text-transform:uppercase;}"
& ".ep-c{font-size:8px;font-weight:700;padding:2px 8px;border-radius:20px;background:rgba(0,166,81,.08);color:#00A651;border:1px solid rgba(0,166,81,.15);}"
& ".ep-a{font-size:8px;font-weight:700;padding:2px 8px;border-radius:20px;background:rgba(211,47,47,.08);color:#D32F2F;border:1px solid rgba(211,47,47,.15);}"
& ".ep-ap{font-size:8px;font-weight:700;padding:2px 8px;border-radius:20px;background:rgba(217,119,6,.1);color:#D97706;border:1px solid rgba(217,119,6,.25);}"
& ".ep-p{font-size:8px;font-weight:700;padding:2px 8px;border-radius:20px;background:rgba(0,120,212,.08);color:#0078D4;border:1px solid rgba(0,120,212,.2);}"
& ".c5-comp{display:flex;align-items:center;gap:5px;}"
& ".cam-btn{font-size:13px;cursor:pointer;opacity:.85;transition:opacity .15s;line-height:1;}"
& ".cam-btn:hover{opacity:1;}"
& ".cam-no{font-size:13px;opacity:.25;line-height:1;cursor:default;}"
& ".foot{display:flex;gap:14px;padding-top:6px;border-top:1px solid #F3F4F6;margin-top:4px;flex-shrink:0;}"
& ".fi{display:flex;align-items:center;gap:4px;}"
& ".fl{font-size:8px;color:#9CA3AF;}"
& ".fv{font-size:10px;font-weight:700;}"
& ".m-ov{display:none;position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:999;align-items:center;justify-content:center;}"
& ".m-ov.show{display:flex;}"
& ".m-box{background:#fff;border-radius:14px;padding:22px 26px;width:320px;box-shadow:0 12px 40px rgba(0,0,0,.25);border-top:3px solid #0078D4;}"
& ".m-tit{font-size:12px;font-weight:800;color:#111827;margin-bottom:4px;}"
& ".m-badge{display:inline-block;font-size:7px;font-weight:700;padding:2px 8px;border-radius:10px;margin-bottom:14px;}"
& ".m-op-card{display:flex;align-items:center;gap:10px;background:#F9FAFB;padding:10px 12px;border-radius:10px;border:1px solid #F3F4F6;margin-bottom:14px;}"
& ".m-op-img{width:38px;height:38px;border-radius:50%;object-fit:cover;background:#E5E7EB;border:2px solid #fff;box-shadow:0 2px 6px rgba(0,0,0,.08);}"
& ".m-op-name{font-size:10px;font-weight:700;color:#111827;}"
& ".m-op-lbl{font-size:7px;color:#9CA3AF;text-transform:uppercase;}"
& ".m-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;}"
& ".m-lab{font-size:7px;font-weight:700;color:#9CA3AF;text-transform:uppercase;margin-bottom:1px;}"
& ".m-val{font-size:10px;font-weight:600;color:#374151;}"
& ".m-motivo-section{margin-top:14px;background:#FFFBEB;border:1px solid #FDE68A;border-radius:8px;padding:10px 12px;}"
& ".m-mot-lbl{font-size:7px;font-weight:700;color:#D97706;text-transform:uppercase;margin-bottom:4px;}"
& ".m-mot{font-size:10px;color:#374151;line-height:1.5;}"
& ".m-cls{margin-top:16px;width:100%;padding:9px;border-radius:8px;border:none;background:#F3F4F6;color:#374151;font-size:11px;font-weight:700;cursor:pointer;}"
& ".m-cls:hover{background:#E5E7EB;}"
& ".ev-ov{display:none;position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:1000;align-items:center;justify-content:center;}"
& ".ev-ov.show{display:flex;}"
& ".ev-box{background:#fff;border-radius:14px;overflow:hidden;max-width:480px;width:92%;box-shadow:0 16px 48px rgba(0,0,0,.4);}"
& ".ev-head{background:#00A651;padding:12px 16px;display:flex;align-items:center;justify-content:space-between;}"
& ".ev-head-title{font-size:11px;font-weight:700;color:#fff;}"
& ".ev-head-sub{font-size:9px;color:rgba(255,255,255,.75);margin-top:1px;}"
& ".ev-cls{background:none;border:none;color:#fff;font-size:16px;cursor:pointer;padding:2px 6px;border-radius:4px;line-height:1;}"
& ".ev-cls:hover{background:rgba(255,255,255,.2);}"
& ".ev-img-wrap{background:#F3F4F6;display:flex;align-items:center;justify-content:center;min-height:200px;}"
& ".ev-img{width:100%;display:block;max-height:360px;object-fit:contain;}"
& ".ev-no-img{padding:40px 20px;text-align:center;}"
& ".ev-no-ico{font-size:32px;opacity:.3;margin-bottom:8px;}"
& ".ev-no-txt{font-size:10px;color:#9CA3AF;}"
& ".ev-foot{padding:10px 16px;font-size:9px;color:#9CA3AF;text-align:center;border-top:1px solid #F3F4F6;}"
& "</style>"

& "<div class=wrap>"
& "<div class=g-hdr>"
& "<span class=g-title>Máquinas ECILT · " & _areaLabel & "</span>"
& "<span class=g-ctx>" & FORMAT(_total,"0") & " registros · " & FORMAT([% Cumplimiento],"0.0%") & " cumplimiento global</span>"
& "</div>"
& "<div class=lin-tabs id=lin-tabs></div>"
& "<div class=cards-zone>"
& "<button class=nav-btn onclick=""document.getElementById('maq-row').scrollBy({left:-300,behavior:'smooth'})"">◀</button>"
& "<div class=maq-row id=maq-row>" & _filas & _noImpl & "</div>"
& "<button class=nav-btn onclick=""document.getElementById('maq-row').scrollBy({left:300,behavior:'smooth'})"">▶</button>"
& "</div>"
& "<div class=table-zone>"
& "<div class=t-hdr>"
& "<div><div class=t-hdr-title id=t-title>Últimas actividades · " & _areaLabel & "</div>"
& "<div class=t-hdr-sub id=t-sub>⚠ Atrasadas · Pendientes · Completadas</div></div>"
& "<button class=clear-btn id=clear-btn onclick='clearMaq()'>✕ Ver todas</button>"
& "</div>"
& "<div class=thdr><div>Tarea</div><div>Tipo</div><div>Frec.</div><div>Fecha</div><div>Estado</div><div>Turno</div></div>"
& "<div class=dscroll id=dscroll>" & _detalleFilas & "</div>"
& "<div class=foot>"
& "<div class=fi><span class=fl>Total</span><span class=fv style=color:#111827>" & FORMAT(_total,"0") & "</span></div>"
& "<div class=fi><span class=fl style=color:#00A651>✓ Completadas</span><span class=fv style=color:#00A651>" & FORMAT(_comp,"0") & "</span></div>"
& "<div class=fi><span class=fl style=color:#D32F2F>⚠ Atrasadas</span><span class=fv style=color:#D32F2F>" & FORMAT(_atr,"0") & "</span></div>"
& "</div></div></div>"

& "<script>"
& "var AREAS={'Packaging':['Latas','Botellas'],'Utilidades':['Utilidades'],'Brewing':['Cocimiento','Fermentacion','Filtracion']};"
& "var selArea='" & _areaJS & "';"
& "var selLin=null;var selMaq=null;"
& "document.addEventListener('DOMContentLoaded',function(){init();});"
& "if(document.readyState!=='loading'){init();}"
& "function init(){var linSet={};document.querySelectorAll('.mc[data-lin]').forEach(function(c){linSet[c.getAttribute('data-lin')]=c.getAttribute('data-area');});window._linMap=linSet;applyArea(selArea);}"
& "function applyArea(area){var linTabsEl=document.getElementById('lin-tabs');linTabsEl.innerHTML='';var lins=[];Object.keys(window._linMap||{}).forEach(function(l){var a=window._linMap[l];if(!area||a===area)lins.push(l);});lins.sort();lins.forEach(function(l){var b=document.createElement('div');b.className='ltab';b.textContent=l;b.setAttribute('data-lin',l);b.onclick=function(){selectLin(this);};linTabsEl.appendChild(b);});filterCards(area,'');filterRows(area,'',null);var vis=document.querySelectorAll('.mc:not(.hidden):not(.nd)');if(vis.length===1)selectMaq(vis[0]);}"
& "function selectLin(tab){var lin=tab.getAttribute('data-lin');if(selLin===lin){selLin=null;selMaq=null;document.querySelectorAll('.ltab').forEach(function(t){t.classList.remove('active');});filterCards(selArea,'');filterRows(selArea,'',null);document.getElementById('t-title').textContent='Últimas actividades · '+(selArea||'Todas las áreas');document.getElementById('clear-btn').style.display='none';return;}selLin=lin;selMaq=null;document.querySelectorAll('.ltab').forEach(function(t){t.classList.remove('active');});tab.classList.add('active');filterCards(selArea,lin);filterRows(selArea,lin,null);document.getElementById('t-title').textContent='Últimas actividades · '+lin;document.getElementById('clear-btn').style.display='none';var vis=document.querySelectorAll('.mc:not(.hidden):not(.nd)');if(vis.length===1)selectMaq(vis[0]);}"
& "function selectMaq(card){if(card.classList.contains('nd'))return;var id=card.getAttribute('data-id');var nom=card.getAttribute('data-nom');if(selMaq===id){clearMaq();return;}selMaq=id;document.querySelectorAll('.mc').forEach(function(c){c.classList.remove('selected');});card.classList.add('selected');filterRows(selArea,selLin,id);var shown=document.querySelectorAll('.drow:not(.hidden)').length;document.getElementById('t-title').textContent=nom;document.getElementById('t-sub').textContent=shown+' registros';document.getElementById('clear-btn').style.display='block';document.getElementById('dscroll').scrollTop=0;}"
& "function clearMaq(){selMaq=null;document.querySelectorAll('.mc').forEach(function(c){c.classList.remove('selected');});filterRows(selArea,selLin,null);var tit=selLin?selLin:(selArea||'Todas las áreas');document.getElementById('t-title').textContent='Últimas actividades · '+tit;document.getElementById('t-sub').textContent='⚠ Atrasadas · Pendientes · Completadas';document.getElementById('clear-btn').style.display='none';document.getElementById('dscroll').scrollTop=0;}"
& "function filterCards(area,lin){document.querySelectorAll('.mc').forEach(function(c){var clin=c.getAttribute('data-lin');var carea=c.getAttribute('data-area');var show;if(lin)show=clin===lin;else if(area)show=carea===area;else show=true;c.classList.toggle('hidden',!show);});}"
& "function filterRows(area,lin,maqId){document.querySelectorAll('.drow').forEach(function(r){var rmaq=r.getAttribute('data-maq');var rlin=r.getAttribute('data-lin');var rarea=window._linMap?window._linMap[rlin]||'':'';var rimpl=r.getAttribute('data-impl');var showByScope;if(maqId)showByScope=rmaq===maqId;else if(lin)showByScope=rlin===lin;else if(area)showByScope=rarea===area;else showByScope=rimpl==='1';r.classList.toggle('hidden',!showByScope);});}"
& "document.body.insertAdjacentHTML('beforeend','<div class=m-ov id=m-ov><div class=m-box><div class=m-tit id=md-tarea></div><div class=m-badge id=md-badge></div><div class=m-op-card><img id=md-img class=m-op-img><div><div class=m-op-lbl>Operador</div><div class=m-op-name id=md-op></div></div></div><div class=m-grid><div><div class=m-lab>Máquina</div><div class=m-val id=md-maq></div></div><div><div class=m-lab>Línea</div><div class=m-val id=md-lin></div></div><div><div class=m-lab>Tipo Tarea</div><div class=m-val id=md-tipo></div></div><div><div class=m-lab>Frecuencia</div><div class=m-val id=md-freq></div></div><div><div class=m-lab>Programado</div><div class=m-val id=md-fplan></div></div><div><div class=m-lab>Ejecución</div><div class=m-val id=md-fcomp></div></div><div><div class=m-lab>Turno</div><div class=m-val id=md-turno></div></div><div><div class=m-lab>Estado</div><div class=m-val id=md-est></div></div></div><div id=md-mot-box class=m-motivo-section style=display:none><div class=m-mot-lbl>Motivo / Observación</div><div class=m-mot id=md-mot></div></div><button class=m-cls onclick=closeMotivo()>Cerrar</button></div></div><div class=ev-ov id=ev-ov><div class=ev-box><div class=ev-head><div><div class=ev-head-title>Evidencia de cumplimiento</div><div class=ev-head-sub id=ev-sub></div></div><button class=ev-cls onclick=closeEvidencia()>&#x2715;</button></div><div class=ev-img-wrap id=ev-img-wrap></div><div class=ev-foot>Foto registrada por el operador al completar la tarea</div></div></div>');"
& "document.getElementById('m-ov').addEventListener('click',function(e){if(e.target===this)closeMotivo();});"
& "document.getElementById('ev-ov').addEventListener('click',function(e){if(e.target===this)closeEvidencia();});"
& "function onRowClick(row){var d=row.dataset;document.getElementById('md-tarea').textContent=d.tarea||'';var b=document.getElementById('md-badge');b.textContent=d.estado||'';var colors={'Atrasado':'#D32F2F','Aplazado':'#D97706','Pendiente':'#0078D4','Completado':'#00A651'};var c=colors[d.estado]||'#6B7280';b.style.background=c+'18';b.style.color=c;document.getElementById('md-op').textContent=d.op||'Sin asignar';var img=document.getElementById('md-img');img.src=d.opfoto||'';img.onerror=function(){this.src='https://ui-avatars.com/api/?name='+(d.op||'OP').replace(/ /g,'+')+'&background=random&size=76';};document.getElementById('md-maq').textContent=d.maqnom||'';document.getElementById('md-lin').textContent=d.linea||'';document.getElementById('md-tipo').textContent=d.tipofull||'';document.getElementById('md-freq').textContent=d.freq||'';document.getElementById('md-fplan').textContent=d.fplan||'';document.getElementById('md-fcomp').textContent=d.fcomp||'';document.getElementById('md-turno').textContent=d.turno||'';var est=document.getElementById('md-est');est.textContent=d.estado||'';est.style.color=c;var mb=document.getElementById('md-mot-box');if(d.motivo&&d.motivo!==''){mb.style.display='block';document.getElementById('md-mot').textContent=d.motivo;}else{mb.style.display='none';}document.getElementById('m-ov').classList.add('show');}"
& "function closeMotivo(){document.getElementById('m-ov').classList.remove('show');}"
& "function showEvidencia(el){event.stopPropagation();var url=el.getAttribute('data-url');var tarea=el.getAttribute('data-tarea');document.getElementById('ev-sub').textContent=tarea;var wrap=document.getElementById('ev-img-wrap');if(url&&url.length>0){var img=document.createElement('img');img.className='ev-img';img.id='ev-img-el';img.src=url;img.onerror=function(){this.parentNode.innerHTML='<div class=ev-no-img><div class=ev-no-ico></div><div class=ev-no-txt>No se pudo cargar la imagen</div></div>';};wrap.innerHTML='';wrap.appendChild(img);}else{wrap.innerHTML='<div class=ev-no-img><div class=ev-no-ico></div><div class=ev-no-txt>No se ha cargado evidencia para esta tarea</div></div>';}document.getElementById('ev-ov').classList.add('show');}"
& "function closeEvidencia(){document.getElementById('ev-ov').classList.remove('show');document.getElementById('ev-img-wrap').innerHTML='';}"
& "</script>"



